### ISSUE TITLE
Any way to download via cookies instead of watir?

### ISSUE THREAD

**Issue by yoonwaiyan** [Austio/ruby-tapas-downloader#14]
I couldn't make this script work in my machine as I have trouble setting up my chromedriver to work. This is the error I have while trying to run the script:

```
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 1.0.11, ~> 1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
0   chromedriver                        0x000000011015a309 chromedriver + 3748617: session not created: This version of ChromeDriver only supports Chrome version 78 (Selenium::WebDriver::Error::SessionNotCreatedError)
	from 1   chromedriver                        0x00000001100ee943 chromedriver + 3307843
	from 2   chromedriver                        0x000000010fe7e44f chromedriver + 750671
	from 3   chromedriver                        0x000000010fddfc5b chromedriver + 101467
	from 4   chromedriver                        0x000000010fddbd51 chromedriver + 85329
	from 5   chromedriver                        0x000000010fe0a217 chromedriver + 274967
	from 6   chromedriver                        0x000000010fe073e3 chromedriver + 263139
	from 7   chromedriver                        0x000000010fde1d8d chromedriver + 109965
	from 8   chromedriver                        0x000000010fde2d25 chromedriver + 113957
	from 9   chromedriver                        0x000000011011d3ef chromedriver + 3498991
	from 10  chromedriver                        0x0000000110129fed chromedriver + 3551213
	from 11  chromedriver                        0x0000000110129d78 chromedriver + 3550584
	from 12  chromedriver                        0x00000001100fc499 chromedriver + 3363993
	from 13  chromedriver                        0x000000011012a848 chromedriver + 3553352
	from 14  chromedriver                        0x0000000110110ea7 chromedriver + 3448487
	from 15  chromedriver                        0x0000000110140404 chromedriver + 3642372
	from 16  chromedriver                        0x00000001101600f7 chromedriver + 3772663
	from 17  libsystem_pthread.dylib             0x00007fff59d22661 _pthread_body + 340
	from 18  libsystem_pthread.dylib             0x00007fff59d2250d _pthread_body + 0
	from 19  libsystem_pthread.dylib             0x00007fff59d21bf9 thread_start + 13
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:99:in `create_session'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/chrome/driver.rb:49:in `initialize'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver.rb:86:in `for'
	from /Users/yoonwaiyan/.asdf/installs/ruby/2.4.2/lib/ruby/gems/2.4.0/gems/watir-6.8.4/lib/watir/browser.rb:48:in `initialize'
	from /Users/yoonwaiyan/Documents/workspace/ruby-tapas-downloader/lib/classes/logged_browser.rb:11:in `new'
	from /Users/yoonwaiyan/Documents/workspace/ruby-tapas-downloader/lib/classes/logged_browser.rb:11:in `browser'
	from /Users/yoonwaiyan/Documents/workspace/ruby-tapas-downloader/lib/classes/logged_browser.rb:5:in `call'
	from ruby-tapas-downloader.rb:15:in `<main>'
```

Tried StackOverflow but failed to make chromedriver works (should I upgrade? downgrade? where to put the driver? `brew cask upgrade chromedriver` doesn't work either). Is it possible to use cookies-based scrapers in place of selenium? Or could you guide me through the webdriver to  make it work on my Macbook?

**Comment by Austio** [comment]
Howdy, Thinking more and more that we need this in a docker file setup for this to reduce gotchas, please feel free to set that up if you want to make a pr

**Comment by yoonwaiyan** [comment]
I'm glad to help make a pr but I need a bit of help on the chromedriver settings. I prepared a Dockerfile and a docker-compose.yml but I couldn't make it work in my Docker image. This is the error I received:

```
$ docker-compose run ruby_tapas_downloader
Traceback (most recent call last):
	17: from ruby-tapas-downloader.rb:15:in `<main>'
	16: from /usr/app/lib/classes/logged_browser.rb:5:in `call'
	15: from /usr/app/lib/classes/logged_browser.rb:11:in `browser'
	14: from /usr/app/lib/classes/logged_browser.rb:11:in `new'
	13: from /usr/local/bundle/gems/watir-6.8.4/lib/watir/browser.rb:48:in `initialize'
	12: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver.rb:85:in `for'
	11: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:44:in `for'
	10: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/common/driver.rb:44:in `new'
	 9: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/chrome/driver.rb:47:in `initialize'
	 8: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
	 7: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
	 6: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
	 5: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	 4: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
	 3: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
	 2: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
	 1: from /usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
/usr/local/bundle/gems/selenium-webdriver-3.11.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': unknown error: cannot find Chrome binary (Selenium::WebDriver::Error::UnknownError)
  (Driver info: chromedriver=72.0.3626.121,platform=Linux 4.9.184-linuxkit x86_64)
```
the chromedriver is installed:
```
$ docker run ruby-tapas-downloader_ruby_tapas_downloader chromedriver -v
ChromeDriver 72.0.3626.121
```

Is there something I'm missing out or I have to install latest version of chromedriver to make it work?

**Comment by Austio** [comment]
hey could you shoot me over the Dockerfile that you are working on?

**Comment by yoonwaiyan** [comment]
Here's the Dockerfile I'm working on:

```
FROM ruby:2.6.5-alpine3.9

RUN apk update && apk upgrade
RUN apk add --no-cache wget xvfb unzip chromium-chromedriver>77.0.3865.75-r0 build-base
RUN which chromedriver

ENV PATH="/usr/bin:${PATH}"

# Setup working directory and add download directory
RUN mkdir /usr/app
WORKDIR /usr/app
COPY . /usr/app
RUN mkdir /usr/app/RubyTapas

# Install Ruby dependencies
COPY Gemfile /usr/app/
COPY Gemfile.lock /usr/app/
RUN bundle install
```

After some research, I think I'm missing out the chrome browser to make this work in my Docker. Will fork out some time later to try install a headless chrome.

**Comment by yoonwaiyan** [comment]
I'm using Firefox geckodriver instead of chrome and it works perfectly. 

To anyone facing this problem especially using macOS, install geckodriver using brew and set MY_BROWSER with symbol works.

```ruby
MY_BROWSER = :firefox
```
